#ifndef MOMENT_FFMPEG__INC_H__
#define MOMENT_FFMPEG__INC_H__


#define MOMENT_FFMPEG__INIT
#define MOMENT_FFMPEG__FFMPEG_CLEANER
#define MOMENT_FFMPEG__CHANNEL_RECORDER


#endif /* MOMENT_FFMPEG__INC_H__ */

