<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'RTMP Статистика' => '',
  'Админы' => '',
  'Активировать' => '',
  'Активный' => '',
  'Время' => '',
  'Все остальные' => '',
  'Все остальные камеры' => '',
  'Главная страница' => '',
  'Емкость' => '',
  'Забаненные' => '',
  'Забанить' => '',
  'Значение' => '',
  'Использованно' => '',
  'Кому' => '',
  'Кто' => '',
  'Мои камеры' => '',
  'Нагрузка ресурсов' => '',
  'Название' => '',
  'Настройки камер изменены' => '',
  'Не публичная' => '',
  'Неактивированный' => '',
  'Ник' => '',
  'Описание' => '',
  'Опубликовать/Скрыть' => '',
  'Перейти на страницу: ' => '',
  'Повысить' => '',
  'Пользователь(и) {action}' => '',
  'Пользовательские логи' => '',
  'Понизить' => '',
  'Почта' => '',
  'Публичная' => '',
  'Публичные камеры' => '',
  'Раздел' => '',
  'Разделы жесткого диска' => '',
  'Свободно' => '',
  'Системные логи' => '',
  'Сообщение' => '',
  'Список админов пуст.<br/>' => '',
  'Список забаненных пуст.<br/>' => '',
  'Список камер пуст.<br/>' => '',
  'Список моих камер пуст.<br/>' => '',
  'Список пользователей пуст.<br/>' => '',
  'Список публичных камер пуст.<br/>' => '',
  'Статистика недоступна' => '',
  'Статистика(100 последних измерений)' => '',
  'Статус' => '',
  'Это админка<br>Ваш К.О.' => '',
  'активирован' => '',
  'далее' => '',
  'забанен' => '',
  'логи пусты' => '',
  'назад' => '',
  'повышен' => '',
  'понижен' => '',
  'разбанен' => '',
  'разбанить' => '',
);
