<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' To ' => '',
  '60 min max' => '',
  '<br/>My cams list is empty.<br/>' => '',
  'Add' => '',
  'Add cam' => '',
  'Archive' => '',
  'Cam not added. Problem with nvr' => '',
  'Cam not changed. Problem with nvr' => '',
  'Cam not deleted. Problem with nvr' => '',
  'Cam successfully added' => '',
  'Cam successfully changed' => '',
  'Cam successfully shared' => '',
  'Cams settings changed' => '',
  'Cams shared for me' => '',
  'Cams successfully deleted' => '',
  'Cams, can be list of cams separated ","' => '',
  'Coordinates' => '',
  'Coordinates must be: "xxx.xxx, yyy.yyy"' => '',
  'Date' => '',
  'Delete' => '',
  'Description' => '',
  'Don\'t record' => '',
  'Don\'t show' => '',
  'Download' => '',
  'Edit' => '',
  'Emails/groups, can be list separated ","' => '',
  'Enable record' => '',
  'Fields marked with an * are required' => '',
  'From ' => '',
  'Go' => '',
  'Go to' => '',
  'Go to {user CP}' => '',
  'High quality' => '',
  'IP address' => '',
  'List cams shared for me is empty.<br/>' => '',
  'Low quality' => '',
  'Low quality stream URL' => '',
  'Mass actions: ' => '',
  'My cams' => '',
  'Name' => '',
  'No cams to show.' => '',
  'Not allowed for you' => '',
  'Owner' => '',
  'Public' => '',
  'Public cams' => '',
  'Public cams list is empty.<br/>' => '',
  'Record' => '',
  'Record {record status}' => '',
  'Record/Don\'t record' => '',
  'Record?' => '',
  'Save' => '',
  'Server' => '',
  'Share' => '',
  'Show' => '',
  'Show on main page' => '',
  'Show/Don\'t show' => '',
  'Show?' => '',
  'Specify the users for whom you want to share cams' => '',
  'Time' => '',
  'Time interval' => '',
  'Time zone' => '',
  'View area' => '',
  'View {cam_name}' => '',
  'You granted access to camera {cam}' => '',
  'You must choose cams to modify' => '',
  'assign' => '',
  'live' => '',
  'min' => '',
  'off' => '',
  'on' => '',
  'open in new window' => '',
  'personal cabinet' => '',
  'there is no record for this period' => '',
  ' До ' => '@@@@',
  'Time interval:' => '@@@@',
  'Time:' => '@@@@',
  'Вам расшарена камера {cam}' => '@@@@',
  'Дата' => '@@@@',
  'От ' => '@@@@',
  'Просмотр {cam_name}' => '@@@@',
  'минут' => '@@@@',
);
