<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Access denied' => '',
  'Add cam fail, problem with nvr, http response: {response}' => '',
  'An account with this email address already exists' => '',
  'An account with this nick already exists' => '',
  'Can not get archive, problem with nvr' => '',
  'Can not get playlist, problem with nvr' => '',
  'Can not get statistics type: {type}' => '',
  'Change cam fail, problem with nvr, http response: {response}' => '',
  'Delete cam fail, problem with nvr, http response: {response}' => '',
  'Error' => '',
  'One of cam is wrong' => '',
  'One of user is wrong' => '',
  'Record on/off fail, problem with nvr' => '',
  'Status already set' => '',
  'There is no such cam' => '',
  'There is no such user' => '',
  'Unixtime get fail, problem with nvr' => '',
  'Wrong action' => '',
  'Wrong cam' => '',
  'Wrong email format' => '',
  'Wrong email or password.' => '',
  'Wrong notify' => '',
  'You are not owner of this cam' => '',
  'Your account is not active. Check your email.' => '',
  'cannot be blank' => '',
  'wrong password' => '',
  'Delete cam fail, problem with nvr, http response:  {response}' => '@@@@',
  'Добавление камеры неудалось, проблема с моментом, http ответ: {response}' => '@@@@',
  'Изменение камеры неудалось, проблема с моментом, http ответ: {response}' => '@@@@',
  'Неправильный формат email' => '@@@@',
  'Неудалось получить unixtime, проблема с моментом' => '@@@@',
  'Неудалось получить архив, проблема с моментом' => '@@@@',
  'Неудалось получить плейлист, проблема с моментом' => '@@@@',
  'Неудалось получить статистику вида: {type}, проблема с моментом' => '@@@@',
  'Неудалось поставить или снять запись, проблема с моментом' => '@@@@',
  'Удаление камеры неудалось, проблема с моментом, http ответ: {response}' => '@@@@',
);
