<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Account activation' => '',
  'Change' => '',
  'Code:' => '',
  'Enter password again:' => '',
  'Enter password:' => '',
  'Enter your email:' => '',
  'Enter your nick:' => '',
  'Go to site' => '',
  'Hello {nick},<br/><br/>Your activation code: {code}<br/>{link}' => '',
  'Letter for password recovery was sended to your email' => '',
  'Login' => '',
  'Login form' => '',
  'Nick' => '',
  'Password' => '',
  'Password can\'t be empty.' => '',
  'Password recovery' => '',
  'Passwords not equal!' => '',
  'Recovery link: {link}' => '',
  'Register' => '',
  'Registration' => '',
  'Registration form' => '',
  'Registration was successful.<br/>To use your account, you need to confirm your email address.<br/>Confirmation code sent to your email.<br/>' => '',
  'Remember me?' => '',
  'Send recovery message' => '',
  'There is no such user' => '',
  'There is no such user.' => '',
  'This user already confirmed his email address.' => '',
  'Wrong code.' => '',
  'You successfully confirmed your email address. Now you can login.' => '',
  'Your email' => '',
  'Your password was successfully changed. go to {login} or {site}' => '',
  'index' => '',
  'login' => '',
  'or' => '',
  '
					Registration was successful.<br/>
					To use your account, you need to confirm your email address.<br/>
					Confirmation code sent to your email.<br/>' => '@@@@',
  '
Recovery link: {link}
' => '@@@@',
  'Hello {nick},<br/><br/>


					Your activation code: {code}<br/> 
					{link}' => '@@@@',
);
