<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '[UTC + 10:30] Lord Howe Standard Time' => '',
  '[UTC + 10] Australian Eastern Standard Time, Vladivostok Standard Time' => '',
  '[UTC + 11:30] Norfolk Island Time' => '',
  '[UTC + 11] Solomon Island Time, Magadan Standard Time' => '',
  '[UTC + 12:45] Chatham Islands Time' => '',
  '[UTC + 12] New Zealand Time, Fiji Time, Kamchatka Standard Time' => '',
  '[UTC + 13] Tonga Time, Phoenix Islands Time' => '',
  '[UTC + 14] Line Island Time' => '',
  '[UTC + 1] Central European Time, West African Time' => '',
  '[UTC + 2] Eastern European Time, Central African Time' => '',
  '[UTC + 3:30] Iran Standard Time' => '',
  '[UTC + 3] Moscow Standard Time, Eastern African Time' => '',
  '[UTC + 4:30] Afghanistan Time' => '',
  '[UTC + 4] Gulf Standard Time, Samara Standard Time' => '',
  '[UTC + 5:30] Indian Standard Time, Sri Lanka Time' => '',
  '[UTC + 5:45] Nepal Time' => '',
  '[UTC + 5] Pakistan Standard Time, Yekaterinburg Standard Time' => '',
  '[UTC + 6:30] Cocos Islands Time, Myanmar Time' => '',
  '[UTC + 6] Bangladesh Time, Bhutan Time, Novosibirsk Standard Time' => '',
  '[UTC + 7] Indochina Time, Krasnoyarsk Standard Time' => '',
  '[UTC + 8:45] Southeastern Western Australia Standard Time' => '',
  '[UTC + 8] Chinese Standard Time, Australian Western Standard Time, Irkutsk Standard Time' => '',
  '[UTC + 9:30] Australian Central Standard Time' => '',
  '[UTC + 9] Japan Standard Time, Korea Standard Time, Chita Standard Time' => '',
  '[UTC - 10] Hawaii-Aleutian Standard Time, Cook Island Time' => '',
  '[UTC - 11] Niue Time, Samoa Standard Time' => '',
  '[UTC - 12] Baker Island Time' => '',
  '[UTC - 1] Azores Standard Time, Cape Verde Time, Eastern Greenland Time' => '',
  '[UTC - 2] Fernando de Noronha Time, South Georgia &amp; the South Sandwich Islands Time' => '',
  '[UTC - 3:30] Newfoundland Standard Time' => '',
  '[UTC - 3] Amazon Standard Time, Central Greenland Time' => '',
  '[UTC - 4:30] Venezuelan Standard Time' => '',
  '[UTC - 4] Atlantic Standard Time' => '',
  '[UTC - 5] Eastern Standard Time' => '',
  '[UTC - 6] Central Standard Time' => '',
  '[UTC - 7] Mountain Standard Time' => '',
  '[UTC - 8] Pacific Standard Time' => '',
  '[UTC - 9:30] Marquesas Islands Time' => '',
  '[UTC - 9] Alaska Standard Time, Gambier Island Time' => '',
  '[UTC] Western European Time, Greenwich Mean Time' => '',
);
