<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Accept' => '',
  'Accepted' => '',
  'Action' => '',
  'Approve' => '',
  'Change password' => '',
  'Decline' => '',
  'Declined' => '',
  'Disapprove' => '',
  'From' => '',
  'Message' => '',
  'New notifications' => '',
  'New password' => '',
  'Old notifications' => '',
  'Old password' => '',
  'Password successfully changed' => '',
  'Save' => '',
  'Show archive by time:' => '',
  'There is no actions' => '',
  'There is no new notifications' => '',
  'There is no old notifications' => '',
  'Time zone' => '',
  'Time zone successfully changed' => '',
  'Timezone settings' => '',
  'User decline shared cam' => '',
  'cam' => '',
  'save' => '',
  'user' => '',
  'Одобрить' => '@@@@',
  'Отклонить' => '@@@@',
);
