<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' mailer is not supported.' => '',
  'Cannot set or reset variable: ' => '',
  'Could not access file: ' => '',
  'Could not execute: ' => '',
  'Could not instantiate mail function.' => '',
  'File Error: Could not open file: ' => '',
  'Invalid address' => '',
  'Message body empty' => '',
  'SMTP Connect() failed.' => '',
  'SMTP Error: Could not authenticate.' => '',
  'SMTP Error: Could not connect to SMTP host.' => '',
  'SMTP Error: Data not accepted.' => '',
  'SMTP Error: The following recipients failed: ' => '',
  'SMTP server error: ' => '',
  'Signing Error: ' => '',
  'The following From address failed: ' => '',
  'Unknown encoding: ' => '',
  'You must provide at least one recipient email address.' => '',
  'You need an HTML capable viewer to read this message.' => '',
);
