<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'RTMP statistics' => 'RTMP Статистика',
  'Admins' => 'Админы',
  'Activate' => 'Активировать',
  'Activated' => 'Активный',
  'Time' => 'Время',
  'Other' => 'Все остальные',
  'Other cams' => 'Все остальные камеры',
  'Index page' => 'Главная страница',
  'Size' => 'Емкость',
  'Banned' => 'Забаненные',
  'Ban' => 'Забанить',
  'Value' => 'Значение',
  'Used' => 'Использованно',
  'To' => 'Кому',
  'From' => 'Кто',
  'My cams' => 'Мои камеры',
  'System load' => 'Загрузка системы',
  'Name' => 'Название',
  'Cams settings successfully changed' => 'Настройки камер изменены',
  'Not public' => 'Не публичная',
  'Not activated' => 'Неактивированный',
  'Nick' => 'Ник',
  'Description' => 'Описание',
  'Public/Not public' => 'Публичная/Не публичная',
  'Go to page: ' => 'Перейти на страницу: ',
  'Up' => 'Повысить',
  'Users {action}' => 'Пользователь(и) {action}',
  'User logs' => 'Пользовательские логи',
  'Down' => 'Понизить',
  'Email' => 'Почта',
  'Public' => 'Публичная',
  'Public cams' => 'Публичные камеры',
  'Partition' => 'Раздел',
  'HDD partitions' => 'Разделы жесткого диска',
  'Free' => 'Свободно',
  'System logs' => 'Системные логи',
  'Message' => 'Сообщение',
  'Admins list is empty.<br/>' => 'Список админов пуст.<br/>',
  'Operators list is empty.<br/>' => 'Список операторов пуст.<br/>',
  'Viewers list is empty.<br/>' => 'Список наблюдателей пуст.<br/>',
  'Banned list is empty.<br/>' => 'Список забаненных пуст.<br/>',
  'Cams list is empty.<br/>' => 'Список камер пуст.<br/>',
  'My cams list is empty.<br/>' => 'Список моих камер пуст.<br/>',
  'Users list is empty.<br/>' => 'Список пользователей пуст.<br/>',
  'Public cams list is empty.<br/>' => 'Список публичных камер пуст.<br/>',
  'Statistics not avaiable' => 'Статистика недоступна',
  'Statistics(100 recent changes)' => 'Статистика(100 последних измерений)',
  'Status' => 'Статус',
  'This is admins panel<br>Your CO' => 'Это админка<br>Ваш К.О.',
  'active' => 'активирован',
  'next' => 'далее',
  'banned' => 'забанен',
  'logs empty' => 'логи пусты',
  'prev' => 'назад',
  'increased' => 'повышен',
  'decreased' => 'понижен',
  'unbanned' => 'разбанен',
  'unban' => 'разбанить',
  'System' => 'Система',
  'Viewers' => 'Наблюдатели',
  'Operators' => 'Операторы',
  'All others' => 'Все остальные',
);
