<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<br/>Список моих камер пуст.<br/>' => '',
  'Архив' => '',
  'Выберите кому камеры шарить' => '',
  'Выбор интервала' => '',
  'Для начала выберите камеры' => '',
  'Добавить' => '',
  'Добавить камеру' => '',
  'Записывать' => '',
  'Записывать/Не записывать' => '',
  'Записывать?' => '',
  'Запись {record status}' => '',
  'Заполните поля. * - помечены обязательные' => '',
  'Камер для отображения нет.' => '',
  'Камера не добавлена, проблемы с Moment`ом' => '',
  'Камера не изменена, проблемы с Moment`ом' => '',
  'Камера не удалена, проблемы с Moment`ом' => '',
  'Камера успешно добавлена' => '',
  'Камера успешно изменена' => '',
  'Камера успешно удалена' => '',
  'Камеры удалены' => '',
  'Камеры успешно расшарены' => '',
  'Мои камеры' => '',
  'Название' => '',
  'Настройки камер изменены' => '',
  'Не записывать' => '',
  'Не показывать' => '',
  'Описание' => '',
  'Перейти' => '',
  'Перейти в {user CP}' => '',
  'Показывать' => '',
  'Показывать/Не показывать' => '',
  'Показывать?' => '',
  'Промежуток времени:' => '',
  'Просмотр {cam_name}' => '',
  'Прямой эфир' => '',
  'Публичные камеры' => '',
  'Расшаренные для меня камеры' => '',
  'Расшарить' => '',
  'Редактирование' => '',
  'Редактировать' => '',
  'Скачать' => '',
  'Сохранить' => '',
  'Список публичных камер пуст.<br/>' => '',
  'Список расшареных, для меня камер пуст.<br/>' => '',
  'Удалить' => '',
  'Хозяин' => '',
  'личный кабинет' => '',
  'минут' => '',
);
