<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cam successfully shared' => 'Камера успешно расшарена',
  'Not allowed for you' => 'Вы не можете выполнить это действие',
  'View area' => '',
  'assign' => 'Назначить',
  ' To ' => ' До ',
  '60 min max' => '60 минут макс.',
  '<br/>My cams list is empty.<br/>' => '<br/>Список моих камер пуст.<br/>',
  'Add' => 'Добавить',
  'Add cam' => 'Добавить камеру',
  'Archive' => 'Архив',
  'Cam not added. Problem with nvr' => 'Камера не добавлена, проблемы с nvr',
  'Cam not changed. Problem with nvr' => 'Камера не изменена, проблемы с nvr',
  'Cam not deleted. Problem with nvr' => 'Камера не удалена, проблемы с nvr',
  'Cam successfully added' => 'Камеры успешно расшарены',
  'Cam successfully changed' => 'Камера успешно изменена',
  'Cams settings changed' => 'Настройки камер изменены',
  'Cams shared for me' => 'Расшаренные для меня камеры',
  'Cams successfully deleted' => 'Камеры удалены',
  'Cams, can be list of cams separated ","' => 'Камеры, можно неск. разделять ","',
  'Coordinates' => 'Координаты',
  'Coordinates must be: "xxx.xxx, yyy.yyy"' => 'Координаты должны быть в виде: "xxx.xxx, yyy.yyy"',
  'Date' => 'Дата',
  'Delete' => 'Удалить',
  'Description' => 'Описание',
  'Don\'t record' => 'Не записывать',
  'Don\'t show' => 'Не показывать',
  'Download' => 'Скачать',
  'Edit' => 'Редактировать',
  'Emails/groups, can be list separated ","' => 'Email`ы/Группы, можно неск. разделять ","',
  'Enable record' => 'Включить запись',
  'Fields marked with an * are required' => 'Заполните поля. * - помечены обязательные',
  'From ' => 'От ',
  'Go' => 'Перейти',
  'Go to' => 'Перейти',
  'Go to {user CP}' => 'Перейти в {user CP}',
  'High quality' => 'Высокое качество',
  'IP address' => 'IP адрес',
  'List cams shared for me is empty.<br/>' => 'Список расшареных, для меня камер пуст.<br/>',
  'Low quality' => 'Низкое качество',
  'Low quality stream URL' => 'URL потока низкого качества',
  'Mass actions: ' => 'Массовые действия: ',
  'My cams' => 'Мои камеры',
  'Name' => 'Название',
  'No cams to show.' => 'Камер для отображения нет.',
  'Owner' => 'Хозяин',
  'Public' => 'Публичная',
  'Public cams' => 'Публичные камеры',
  'Public cams list is empty.<br/>' => 'Список публичных камер пуст.<br/>',
  'Record' => 'Запись',
  'Record {record status}' => 'Запись {record status}',
  'Record/Don\'t record' => 'Записывать/Не записывать',
  'Record?' => 'Записывать?',
  'Save' => 'Сохранить',
  'Server' => 'Сервер',
  'Share' => 'Расшарить',
  'Show' => 'Показывать',
  'Show on main page' => 'Показывать на главной',
  'Show/Don\'t show' => 'Показывать/Не показывать',
  'Show?' => 'Показывать?',
  'Specify the users for whom you want to share cams' => 'Выберите кому камеры шарить',
  'Time' => 'Вермя',
  'Time interval' => 'Промежуток времени',
  'Time zone' => 'Временная зона',
  'View {cam_name}' => 'Просмотр {cam_name}',
  'You granted access to camera {cam}' => 'Вам предоставлен доступ к камере {cam}',
  'You must choose cams to modify' => 'Для начала выберите камеры',
  'live' => 'Прямой эфир',
  'min' => 'минут',
  'off' => 'выкл',
  'on' => 'вкл',
  'open in new window' => 'открыть в новом окне',
  'personal cabinet' => 'личный кабинет',
  'there is no record for this period' => 'Нет записи для данного промежутка.',
);
