<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Your account is not active. Check your email.' => 'Вы не активировали учетную запись, проверьте email.',
  'Access denied' => 'Доступ запрещен',
  'An account with this email address already exists' => 'На этот email, уже зарегестрирован пользователь',
  'Can\'t be empty' => 'Не может быть пустым',
  'Can\'t be empty!' => 'Не можеть быть пустым!',
  'Wrong email or password' => 'Неправильный email или пароль.',
  'Wrong email' => 'Неправильный формат email',
  'There is no such cam' => 'Нет такой камеры',
  'An account with this nick already exists' => 'Такой Ник, уже занят',
  'Wrong password' => 'неправильный пароль',
  'There is no such cam' => 'Камера не сушествует',
  'There is no such user' => 'Пользователя не сушествует',
  'You are not owner of this cameras' => 'Камеры вам не принадлежат.',
  'You are not owner of this camera' => 'Камера вам не принадлежит',
  'Add cam fail, problem with moment, http response: ' => 'Добавление камеры неудалось, проблема с моментом, http ответ: ',
  'Change cam fail, problem with moment, http response: ' => 'Изменение камеры неудалось, проблема с моментом, http ответ: ',
  'Delete cam fail, problem with moment, http response: ' => 'Удаление камеры неудалось, проблема с моментом, http ответ: ',
  'Can not get playlist, problem with moment' => 'Неудалось получить плейлист, проблема с моментом',
  'Can not get archive, problem with moment' => 'Неудалось получить архив, проблема с моментом',
  'Can not get statistics type: ' => 'Неудалось получить статистику вида: ',
  ', problem with moment' => ', проблема с моментом',
  'Record on/off fail, problem with moment' => 'Неудалось поставить или снять запись, проблема с моментом',
  'Unixtime get fail, problem with moment' => 'Неудалось получить unixtime, проблема с моментом',
);
