<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Status already set' => 'Статус уже установлен',
  'Wrong email format' => 'неправельный формат email',
  'Access denied' => 'Доступ запрещен',
  'Add cam fail, problem with nvr, http response: {response}' => 'Добавление камеры неудалось, проблема с нвр, http ответ: {response}',
  'An account with this email address already exists' => 'На этот email, уже зарегестрирован пользователь',
  'An account with this nick already exists' => 'Такой Ник, уже занят',
  'Can not get archive, problem with nvr' => 'Неудалось получить архив, проблема с нвр',
  'Can not get playlist, problem with nvr' => 'Неудалось получить плейлист, проблема с нвр',
  'Can not get statistics type: {type}' => 'Неудалось получить статистику вида: {type}',
  'Change cam fail, problem with nvr, http response: {response}' => 'Изменение камеры неудалось, проблема с нвр, http ответ: {response}',
  'Delete cam fail, problem with nvr, http response: {response}' => 'Удаление камеры неудалось, проблема с нвр, http ответ:  {response}',
  'Error' => 'Ошибка',
  'One of cam is wrong' => 'Одна из камер вам не принадлежит',
  'One of user is wrong' => 'Один из польозователей не существует',
  'Record on/off fail, problem with nvr' => 'Неудалось поставить или снять запись, проблема с нвр',
  'There is no such cam' => 'Камера не существует',
  'There is no such user' => 'Пользователя не существует',
  'Unixtime get fail, problem with nvr' => 'Неудалось получить unixtime, проблема с нвр',
  'Wrong action' => 'Нет такого действия',
  'Wrong cam' => 'Нет такой камеры',
  'Wrong email or password.' => 'Неправильный email или пароль.',
  'Wrong notify' => 'Нет такого уведомления',
  'You are not owner of this cam' => 'Камера вам не принадлежит',
  'Your account is not active. Check your email.' => 'Вы не активировали учетную запись, проверьте email.',
  'cannot be blank' => 'Не может быть пустым',
  'wrong password' => 'Неправельный пароль',
);
