<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Admin' => 'Админка',
  'Server statistics' => 'Статистика сервера',
  'Public cams' => 'Публичные камеры',
  'Users' => 'Пользователи',
  'Logs' => 'Логи',
  'Notifications' => 'Уведомления',
  'Cams' => 'Камеры',
  'Screens' => 'Экраны',
  'Manage' => 'Редактировать',
  'Account settings' => 'Настройки профиля',
  'Logout' => 'Выход',
  'Login' => 'Вход',
  'Register' => 'Регистрация',

  'Index' => 'Главная',
  'Personal cabinet' => 'Личный кабинет',
  'Go to site' => 'На сайт',
  'About us' => 'О нас',
);
