<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '
		Регистрация прошла успешно.<br/>
		Для авторизации, вам необходимо подтвердить свой email.<br/>
		Письмо с кодом подтверждения отправлено вам на почту.<br/>' => '',
  '
Здравствуйте {nick},<br/><br/>


					Ваш код активации: {code}<br/>

					<br/>Ссылка для активации:<br/> 
					{link}' => '',
  '
Ссылка для восстановления: {link}
' => '',
  'Активация аккаунта' => '',
  'Ваш email' => '',
  'Ваш пароль успешно изменен.' => '',
  'Введите email и пароль' => '',
  'Введите email:' => '',
  'Введите Ник:' => '',
  'Введите ник, email и пароль' => '',
  'Введите пароль:' => '',
  'Войти' => '',
  'Восстановить' => '',
  'Восстановление пароля' => '',
  'Вы успешно подтвердили свой email. Теперь вы можете авторизоваться.' => '',
  'Данный пользователь, уже подтвердил свой email.' => '',
  'Запомнить вас?' => '',
  'Изменение пароля' => '',
  'Код:' => '',
  'Неправильный код.' => '',
  'Нет такого пользователя' => '',
  'Ник' => '',
  'Пароли не совпадают!' => '',
  'Пароль' => '',
  'Пароль не может быть пустым.' => '',
  'Перейти на сайт' => '',
  'Письмо с данными для восстановления отправлено на ваш email' => '',
  'Подтвердите пароль:' => '',
  'Регистрация' => '',
  'Такого пользователя нет.' => '',
  'или' => '',
  '
Здравствуйте {nick},<br/><br/>


					Ваш код активации: {code}<br/>

					<br/>Ссылка для активации:<br/> 
					{link}' => '@@@@',
  '
Ссылка для восстановления: {link}
' => '@@@@',
);
