<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Registration was successful.<br/>' => 'Регистрация прошла успешно.<br/>',
  'Account activation' => 'Активация аккаунта',
  'Change' => 'Изменить',
  'Code:' => 'Код:',
  'Enter password again:' => 'Повторите пароль:',
  'Enter password:' => 'Введите пароль:',
  'Enter your email:' => 'Введите email:',
  'Enter your nick:' => 'Введите Ник:',
  'Go to site' => 'Перейти на сайт',
  'Hello {nick},<br/><br/>Your activation code: {code}<br/>{link}' => 'Здравствуйте {nick},<br/><br/>Ваш код для активации: {code}<br/>{link}',
  'Letter for password recovery was sended to your email' => 'Письмо с данными для восстановления отправлено на ваш email',
  'Login' => 'Войти',
  'Login form' => 'Форма авторизации',
  'Nick' => 'Ник',
  'Password' => 'Пароль',
  'Password can\'t be empty.' => 'Пароль не может быть пустым.',
  'Password recovery' => 'Восстановление пароля',
  'Passwords not equal!' => 'Пароли не совпадают!',
  'Recovery link: {link}' => 'Ссылка для восстановления: {link}',
  'Register' => 'Регистрация',
  'Registration' => 'Регистрация',
  'Registration form' => 'Форма регистрации',
  'Registration was successful.<br/>To use your account, you need to confirm your email address.<br/>Confirmation code sent to your email.<br/>' => 'Регистрация прошла успешно.<br/>Для того что бы войти вам нужно сначал подтвердить ваш email.<br/>Код для потдверждения отправлен вам на email.<br/>',
  'Remember me?' => 'Запомнить Вас?',
  'Send recovery message' => 'Послать сообщение для восстановления',
  'There is no such user' => 'Нет такого пользователя',
  'There is no such user.' => 'Такого пользователя нет.',
  'This user already confirmed his email address.' => 'Данный пользователь, уже подтвердил свой email.',
  'Wrong code.' => 'Неправильный код.',
  'You successfully confirmed your email address. Now you can login.' => 'Ваш email успешно подтвержден. Теперь вы можете войти.',
  'Your email' => 'Ваш email',
  'Your password was successfully changed. go to {login} or {site}' => 'Ваш пароль успешно изменен. Вы можете перейти {login} или {site}',
  'index' => 'Главная',
  'login' => 'Вход',
  'or' => 'или',
);
