<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'My screens' => 'Мои экраны',
  'All screens' => 'Все экраны',
  'Add screen' => 'Добавить экран',
  'User ID' => 'ID владельца',
  'Name' => 'Название',
  'Edit' => 'Редакрировать',
  'Delete' => 'Удалить',
  'My screens list is empty.' => 'Список моих экранов пуст.',
  'Screen name' => 'Название экрана',
  'Screen successfully added' => 'Экран добавлен',
  'Screen successfully deleted' => 'Экран удален',
  'Error add screen' => 'Ошибка добавления экрана',
  'New screen' => 'Новый экран',
  'Edit screen' => 'Редактирование экрана',
  'Add cam' => 'Добавить камеру',
  'Delete' => 'Удалить',
  'Cam' => 'Камера',
  'Descr' => 'Описание',
  'Save' => 'Сохранить',
);
