<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Accept' => 'Принять',
  'Accepted' => 'Принята',
  'Action' => 'Действие',
  'Approve' => 'Одобрить',
  'Decline' => 'Отклонить',
  'Declined' => 'Не принята',
  'Disapprove' => 'Отклонить',
  'There is no actions' => 'Нет действий',
  'User decline shared cam' => 'Пользователь отклонил камеру',
  'save' => 'Сохранить',
  'Change password' => 'Изменение пароля',
  'From' => 'Инициатор',
  'Message' => 'Сообщение',
  'New notifications' => 'Новые уведомления',
  'New password' => 'Новый пароль',
  'Old notifications' => 'Старые уведомления',
  'Old password' => 'Старый пароль',
  'Password successfully changed' => 'Пароль успешно изменен',
  'Save' => 'Сохранить',
  'Show archive by time:' => 'показывать архив во времени:',
  'There is no new notifications' => 'Нет новых уведомлений',
  'There is no old notifications' => 'Нет старых уведомлений',
  'Time zone' => 'Часовой пояс',
  'Time zone successfully changed' => 'Часовой пояс успешно изменен',
  'Timezone settings' => 'Настройки часового пояса',
  'cam' => 'камеры',
  'user' => 'пользователя',
);
