<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' mailer is not supported.' => ' mailer не поддерживается.',
  'Cannot set or reset variable: ' => 'Невозможно установить переменную: ',
  'Could not access file: ' => 'Нет доступа к файлу: ',
  'Could not execute: ' => 'Невозможно выполнить: ',
  'Could not instantiate mail function.' => 'Невозможно инициализировать отправку письма.',
  'File Error: Could not open file: ' => 'Ошибка файла: невозможно открыть файл: ',
  'Invalid address' => 'Неправильный адрес',
  'Message body empty' => 'Текст сообщения пустой',
  'SMTP Connect() failed.' => 'SMTP Connect() провалился.',
  'SMTP Error: Could not authenticate.' => 'Ошибка SMTP: Невозможно аутентифицироваться',
  'SMTP Error: Could not connect to SMTP host.' => 'Ошибка SMTP: невозможно подключиться к хосту SMTP.',
  'SMTP Error: Data not accepted.' => 'Ошибка SMTP: Данные не получены.',
  'SMTP Error: The following recipients failed: ' => 'Ошибка SMTP: Следующие получатели недоступны: ',
  'SMTP server error: ' => 'Ошибка SMTP сервера: ',
  'Signing Error: ' => 'Ошибка подписи: ',
  'The following From address failed: ' => 'Следующие адреса отправителя недоступны: ',
  'Unknown encoding: ' => 'Неизвестная кодировка: ',
  'You must provide at least one recipient email address.' => 'Вы должны указать хотябы один адрес получателя.',
  'You need an HTML capable viewer to read this message.' => 'Вам необходима возможность просмотрщика HTML для чтения этого сообщения.',
);
