<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'RTMP statistics' => 'RTMP 统计',
  'Admins' => '管理员',
  'Activate' => '激活',
  'Activated' => '已激活',
  'Time' => '时间',
  'Other' => '其它',
  'Other cams' => '其它摄像机',
  'Index page' => '主页',
  'Size' => '尺寸',
  'Banned' => '被禁的',
  'Ban' => '禁止',
  'Value' => '值',
  'Used' => '用于',
  'To' => '至',
  'From' => '从',
  'My cams' => '我的摄像机',
  'System load' => '系统负载',
  'Name' => '名称',
  'Cams settings successfully changed' => '摄像机设置成功变更',
  'Not public' => '未公开',
  'Not activated' => '未激活',
  'Nick' => '昵称',
  'Description' => '描述',
  'Public/Not public' => '公开/未公开',
  'Go to page: ' => '转到页： ',
  'Up' => '上',
  'Users {action}' => '用户 {action} ',
  'User logs' => '禁止',
  'Down' => '下',
  'Email' => '邮箱',
  'Public' => '公共',
  'Public cams' => '公共摄像机',
  'Partition' => '分区',
  'HDD partitions' => '硬盘分区',
  'Free' => '空闲',
  'System logs' => '系统运行记录',
  'Message' => '信息',
  'Admins list is empty.<br/>' => '管理员列表是空的。<br/>',
  'Operators list is empty.<br/>' => '操作员列表是空的。<br/>',
  'Viewers list is empty.<br/>' => '监视器列表是空的。<br/>',
  'Banned list is empty.<br/>' => '禁止列表是空的。<br/>',
  'Cams list is empty.<br/>' => '摄像机列表是空的。<br/>',
  'My cams list is empty.<br/>' => '我的摄像机列表是空的。<br/>',
  'Users list is empty.<br/>' => '用户列表是空的。<br/>',
  'Public cams list is empty.<br/>' => '公共摄像机列表是空的。<br/>',
  'Statistics not avaiable' => '统计不可用',
  'Statistics(100 recent changes)' => '统计（最近100个变化）',
  'Status' => '状态',
  'This is admins panel<br>Your CO' => '这是管理员列表<br>呵呵',
  'active' => '激活',
  'next' => '下一个',
  'banned' => '被禁的',
  'logs empty' => '日志空',
  'prev' => '上一个',
  'increased' => '增加的',
  'decreased' => '减少的',
  'unbanned' => '解禁',
  'unban' => '准许',
  'System' => '系统',
  'Viewers' => '监视器',
  'Operators' => '操作员',
  'All others' => '所有其它',
);
