<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<br/>My cams list is empty.<br/>' => '<br/>我的摄像头列表是空的。<br/>',
  'Archive' => '档案文件',
  'Specify the users for whom you want to share cams' => '指定摄像机的共享用户',
  'Select interval' => '选择时间间隔',
  'You must choose cams to modify' => '您必须选择摄像头更改',
  'Add' => '增加',
  'Add cam' => '增加摄像机',
  'Record enabled' => '启用录像',
  'Record/Don\'t record' => '录像/不录像',
  'Record?' => '录像？',
  'Record {record status}' => '记录 {记录状态}',
  'Fields marked with an * are required' => '标记*的字段是必需的',
  'No cams to show.' => '摄像机不显示。',
  'Cam not added. Problem with moment' => '该摄像机还没有被添加，实时问题',
  'Cam not changed. Problem with moment' => '该摄像机还没有被更改，实时问题',
  'Cam not deleted. Problem with moment' => '该摄像机还没有删除，实时问题',
  'Cam successfully added' => '该摄像机成功添加',
  'Cam successfully changed' => '该摄像机成功更改',
  'Cam successfully deleted' => '该摄像机成功删除',
  'Cams successfully deleted' => '摄像机批量删除成功',
  'Cam successfully added' => '该摄像机成功添加',
  'My cams' => '我的摄像机',
  'Name' => '名称',
  'Cams settings changed' => '摄像机设置改变',
  'Don\'t record' => '不录像',
  'Don\'t show' => '不显示',
  'Description' => '描述',
  'Go to' => '转到',
  'Go to {user CP}' => '转到{user CP}',
  'Show' => '显示',
  'Show/Don\'t show' => '显示/不显示',
  'Show?' => '显示？',
  'Time interval:' => '时间间隔',
  '{cam_name} view' => '预览 {cam_name}',
  'Real time' => '实际时间',
  'Public cams' => '公共摄像机',
  'Cams shared for me' => '摄像机对我共享',
  'Share' => '共享',
  'Edit' => '编辑',
  'Edit' => '编辑',
  'Download' => '下载',
  'Save' => '保存',
  'Public cams list is empty.<br/>' => '公共摄像机列表是空的。<br/>',
  'List cams shared for me is empty.<br/>' => '我的摄像机共享列表是空的。<br/>',
  'Delete' => '删除',
  'Owner' => '所有者',
  'personal cabinet' => '私人空间',
  'minutes' => '分钟',
  'Date' => '日期',
  'Time' => '时间',
  'Go' => '去',
  'on'  => '开',
  'off' => '关',
  'High quality' => '高质量',
  'Low quality' => '低质量',
  'Coordinates must be "xxx.xxx, yyy.yyy"' => '坐标格式必须是: "xxx.xxx, yyy.yyy"',
  'Low quality stream URL' => '低质量视频流URL链接',
  'Show on main page' => '在主页上显示',
  'Coordinates' => '坐标',
  'Enable record' => '使能录像',
  'Time zone' => '时区',
  'You granted access to camera' => '您有权访问摄像头',
  'Cams, can be list of cams separated ","' => '摄像机可用","分隔开',
  'Emails/groups, can be list separated ","' => '邮箱/群组可用","分隔开',
  'open in new window' => '在新窗口中打开',
);
