<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Вы не активировали учетную запись, проверьте email.' => '',
  'Доступ запрещен' => '',
  'На этот email, уже зарегестрирован пользователь' => '',
  'Не может быть пустым' => '',
  'Не можеть быть пустым!' => '',
  'Неправильный email или пароль.' => '',
  'Неправильный формат email' => '',
  'Нет такой камеры' => '',
  'Такой Ник, уже занят' => '',
  'неправильный пароль' => '',
);
