<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Your account is not active. Check your email.' => '您的账户没有激活，请检查您的电子邮件。',
  'Access denied' => '拒绝访问',
  'An account with this email address already exists' => '该邮箱已被使用',
  'Can\'t be empty' => '不能为空',
  'Can\'t be empty!' => '不能为空！',
  'Wrong email or password' => '错误的邮箱或密码',
  'Wrong email' => '错误的邮箱',
  'There is no such cam' => '不存在此摄像机',
  'An account with this nick already exists' => '此昵称已存在',
  'Wrong password' => '密码错误',
  'There is no such cam' => '不存在此摄像机',
  'There is no such user' => '不存在此用户',
  'You are not owner of this cameras' => '您并不拥有这些摄像机',	
  'You are not owner of this camera' => '您不拥有此摄像机',
  'Add cam fail, problem with moment, http response: ' => '添加摄像机失败，实时问题，http响应： ',
  'Change cam fail, problem with moment, http response: ' => '变更摄像机失败，实时问题，http响应： ',
  'Delete cam fail, problem with moment, http response: ' => '删除摄像机失败，实时问题，http响应： ',
  'Can not get playlist, problem with moment' => '未能获得播放列表，实时问题',
  'Can not get archive, problem with moment' => '未能获得档案文件，实时问题',
  'Can not get statistics type: ' => '未能获得统计数据类型： ',
  ', problem with moment' => '，实时问题',
  'Record on/off fail, problem with moment' => '开关录像失败，实时问题',
  'Unixtime get fail, problem with moment' => 'Unix时间戳获取失败，实时问题',
);
