<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Logout [{nick}]' => '',
  'Main' => '',
  'Servers' => '',
  'Settings' => '',
  'Updater' => '',
  'About us' => '@@关于我们@@',
  'Go to site' => '@@进入网站@@',
  'Index' => '@@索引@@',
  'Logout' => '@@注销@@',
  'Personal cabinet' => '@@私人文件柜@@',
  'Server statistics' => '@@服务器统计信息@@',
  'Account settings' => '账户设置',
  'Admin' => '管理',
  'Cams' => '摄像机',
  'Login' => '登录',
  'Logs' => '日志',
  'Manage' => '编辑',
  'Notifications' => '通知',
  'Public cams' => '公共摄像头',
  'Register' => '注册',
  'Screens' => '屏幕',
  'Users' => '用户',
);
