<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'My screens' => '我的屏幕',
  'All screens' => '所有的屏幕',
  'Add screen' => '增加屏幕',
  'User ID' => '用户ID',
  'Name' => '名称',
  'Edit' => '编辑',
  'Delete' => '删除',
  'My screens list is empty.' => '我的屏幕列表是空的',
  'Screen name' => '屏幕名称',
  'Screen successfully added' => '屏幕成功添加',
  'Screen successfully deleted' => '屏幕成功删除',
  'Error add screen' => '错误添加屏幕',
  'New screen' => '新屏幕',
  'Edit screen' => '编辑屏幕',
  'Add cam' => '增加摄像机',
  'Delete' => '删除',
  'Cam' => '摄像机',
  'Descr' => '备注',
  'Save' => '保存',
);
