<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Accept' => '',
  'Accepted' => '',
  'Action' => '',
  'Approve' => '',
  'Decline' => '',
  'Declined' => '',
  'Disapprove' => '',
  'There is no actions' => '',
  'User approve shared cam' => '',
  'User decline shared cam' => '',
  'save' => '',
  'Add screen' => '@@增加屏幕@@',
  'Edit' => '@@编辑@@',
  'My screens' => '@@我的屏幕@@',
  'Change password' => '修改密码',
  'From' => '来自',
  'Message' => '信息',
  'New notifications' => '新通知',
  'New password' => '新密码',
  'Old notifications' => '旧通知',
  'Old password' => '旧密码',
  'Password successfully changed' => '密码成功变更',
  'Save' => '保存',
  'Show archive by time:' => '按时间显示档案',
  'There is no new notifications' => '没有新的通知',
  'There is no old notifications' => '没有旧的通知',
  'Time zone' => '时区',
  'Time zone successfully changed' => '时区成功变更',
  'Timezone settings' => '时区设置',
  'cam' => '摄像机',
  'user' => '用户',
);
