<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' mailer is not supported.' => ' 不支持邮件。',
  'Cannot set or reset variable: ' => '不能设置或重设变量： ',
  'Could not access file: ' => '无法访问该文件： ',
  'Could not execute: ' => '无法执行： ',
  'Could not instantiate mail function.' => '无法实例化邮件功能。',
  'File Error: Could not open file: ' => '文件错误：无法打开文件： ',
  'Invalid address' => '无效地址',
  'Message body empty' => '信息体空',
  'SMTP Connect() failed.' => 'SMTP连接()失败',
  'SMTP Error: Could not authenticate.' => 'SMTP错误：无法验证',
  'SMTP Error: Could not connect to SMTP host.' => 'SMTP错误：无法连接至SMTP主机。',
  'SMTP Error: Data not accepted.' => 'SMTP错误：不接受数据。',
  'SMTP Error: The following recipients failed: ' => 'SMTP错误：以下收件箱被拒绝: ',
  'SMTP server error: ' => 'SMTP服务器错误： ',
  'Signing Error: ' => '错误签名： ',
  'The following From address failed: ' => '下面的发件人地址失败： ',
  'Unknown encoding: ' => '未知编码： ',
  'You must provide at least one recipient email address.' => '您必须提供至少一个收件人的邮箱地址。',
  'You need an HTML capable viewer to read this message.' => '您需要一个HTML浏览器来阅读这个信息',
);
